temperature:
  CustomName:
    default: "My Temperature Sensor"
    persist: true
  TemperatureType:
    description: "Battery, Fridge or Generic"
    persist: true
    default: 2
    min: 0
    max: 2
  Temperature:
    description: "C"
  Pressure:
    description: "hPa"
  Humidity:
    description: "%"
